FROM python:3.7-slim

ARG REQUIREMENTS_FILE=requirements.txt
ARG AVAILABILITY_CHECK_INTERVAL=300

ENV AVAILABILITY_CHECK_INTERVAL=$AVAILABILITY_CHECK_INTERVAL
ENV PYTHONUNBUFFERED=1
ENV APP_HOME=/var/local/inspire_availability_monitor
ENV PYTHONPATH=$APP_HOME

RUN mkdir -p $APP_HOME

COPY $REQUIREMENTS_FILE $APP_HOME
WORKDIR $APP_HOME

RUN pip install --no-cache-dir -r $REQUIREMENTS_FILE

COPY . $APP_HOME

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["run"]
