version: '2'

services:
  inspire-availability-monitor:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
  inspire-reliability-monitor:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes

volumes:
  availability-data:
    driver: rancher-nfs
  reliability-data:
    driver: rancher-nfs
